application: nl-wikipedia
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: .*
  script: main.app

libraries:
- name: ssl
  version: 2.7.11
- name: lxml
  version: 2.3.5
